---
- name: Update app servers
  hosts: app


  tasks:
  - name: Ensure git is installed
    yum:
      name: git
      state: installed

  - name: Ensure myntra is updated
    git:
      repo: https://github.com/ravi2krishna/food.git
      dest: /var/www/html



...


